bot:
  token: 1990692779:AAFWTS6bPTFBIXM3k__ZPspz7zefq5giSb8
  name: Optimalniy_auctionbot
  admin: 213411446
  merchantId: 100
server:
  port: 8072
spring:
  liquibase:
    enabled: true
    contexts: test
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate:format_sql: false
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    #  Note that the hostname, port and database name on url property and username and password properties will be ignored
    #  and it will be used default container values

    url: jdbc:postgresql://localhost:5555/bo1?user=postgres&password=91823God&currentSchema=public
#    url: jdbc:postgresql://localhost:5432/botter?user=postgres&password=91823God&currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 91823God
    hikari:
      schema: public
